language: java
install: ant dist
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
deploy:
  provider: releases
  api_key: "7d5768ecd758ec990ba9a00827e661bb26c9b901"
  file: "dist/lib/ElectroLight-Explorer.jar"
  skip_cleanup: true
  on:
    tags: true


